// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkTgWmFkWfp7dBl6E22JzxRsHk9gZKsqs',
    appId: '1:883692492654:web:1466237aad856505fc537f',
    messagingSenderId: '883692492654',
    projectId: 'my-notes-308aa',
    authDomain: 'my-notes-308aa.firebaseapp.com',
    storageBucket: 'my-notes-308aa.firebasestorage.app',
    measurementId: 'G-DR5DCMBZSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9aVeTTOvJrYhla3T7gNGJ5i2stNyTxKY',
    appId: '1:883692492654:android:b30d100c0b885d5dfc537f',
    messagingSenderId: '883692492654',
    projectId: 'my-notes-308aa',
    storageBucket: 'my-notes-308aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaNmfv0r6gYjMq-Zd0PoNwuO6uSOCTU-w',
    appId: '1:883692492654:ios:1d66029f019dd0b8fc537f',
    messagingSenderId: '883692492654',
    projectId: 'my-notes-308aa',
    storageBucket: 'my-notes-308aa.firebasestorage.app',
    iosBundleId: 'com.makingstuffup.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaNmfv0r6gYjMq-Zd0PoNwuO6uSOCTU-w',
    appId: '1:883692492654:ios:1d66029f019dd0b8fc537f',
    messagingSenderId: '883692492654',
    projectId: 'my-notes-308aa',
    storageBucket: 'my-notes-308aa.firebasestorage.app',
    iosBundleId: 'com.makingstuffup.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkTgWmFkWfp7dBl6E22JzxRsHk9gZKsqs',
    appId: '1:883692492654:web:e9e48ca11cb6a83afc537f',
    messagingSenderId: '883692492654',
    projectId: 'my-notes-308aa',
    authDomain: 'my-notes-308aa.firebaseapp.com',
    storageBucket: 'my-notes-308aa.firebasestorage.app',
    measurementId: 'G-P1XR955G38',
  );
}
